In [54]:
import numpy as np 

In [53]:
# Create a numpy array
a = np.array([0, 1, 2, 3, 4])
print(a)

[0 1 2 3 4]


In [4]:
# Check the type of the array
type(a)

numpy.ndarray

In [5]:
# Check the type of the values stored in numpy array
a.dtype

dtype('int32')

In [8]:
# Assign the first element to 100
a[0] = 100
print(a)

[100   1   2   3   4]


In [9]:
# Assign the 5th element to 0
a[4] = 0
print(a)

[100   1   2   3   0]


# slicing

In [10]:
# Slicing the numpy array [start:end]
a[1:4]

array([1, 2, 3])

In [11]:
# Set the fourth element and fifth element to 300 and 400
a[3:5] = 300, 400

In [12]:
#We can also define the steps in slicing, like this: [start:end:step]

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [17]:
# If we don't pass start its considered 0
print(arr[:4])

[1 2 3 4]


In [16]:
# If we don't pass end it considers till the length of array.
print(arr[4:])

[5 6 7]


In [18]:
# If we don't pass step its considered 1
print(arr[1:5:])

[2 3 4 5]


# Attributes

In [26]:
# Get the size

a.size

5

In [27]:
# Get the number of dimensions

a.ndim

1

In [28]:
# Get the shape(:number of elements per axis)

a.shape

(5,)

# Statistical functions

In [38]:
a = np.array([1, -1, 7, 3])

In [39]:
# Get the mean of numpy array
mean = a.mean()
mean

2.5

In [40]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

2.958039891549808

In [43]:
# Get the biggest value in the numpy array

max = a.max()
max

7

In [44]:
# Get the smallest value in the numpy array


min = a.min()
min

-1

In [45]:
#Find the sum of maximum and minimum values 

Sum = (max +min)
Sum

6

# Array Operations

In [62]:
u = np.array([1, 2])
v = np.array([4, 5])

In [63]:
# Numpy Array Addition

z = np.add(u, v)
z

array([5, 7])

In [64]:
# Numpy Array subtraction

s = np.subtract(u, v)
c

array([ 1, -5])

In [65]:
# Numpy Array Multiplication

m = np.multiply(u, v)
m

array([ 4, 10])

In [66]:
# Numpy Array Division
d = np.divide(u, v)
d

array([0.25, 0.4 ])

In [67]:
# Numpy Array dot product

np.dot(u, v)

14

# Exercice

In [69]:
#Convert the list [1, 2, 3, 4, 5] and [6, 7, 8, 9, 10] to numpy arrays arr1 and arr2. 
#Then find the even and odd numbers from 2 different arrays.


arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

even_arr1 = arr1[1:5:2]
print("even for array1",even_arr1)
    
odd_arr1=arr1[0:5:2]
print("odd for array1",odd_arr1)

even_arr2 = arr2[0:5:2]
print("even for array2",even_arr2)
    
odd_arr2=arr2[1:5:2]
print("odd for array2",odd_arr2)

even for array1 [2 4]
odd for array1 [1 3 5]
even for array2 [ 6  8 10]
odd for array2 [7 9]
