# Initialize types of Arrays

In [ ]:
import numpy as np

In [8]:
# 0s matrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# 1s matrix
np.ones((2,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [18]:
#full of a number
np.full((2,2),15)

array([[15, 15],
       [15, 15]])

In [19]:
np.random.rand(2,3)

array([[0.49565025, 0.90982594, 0.92029919],
       [0.79946272, 0.1027992 , 0.42423309]])

In [22]:
np.random.rand(2,3)

array([[0.11133941, 0.35984019, 0.57380409],
       [0.96233183, 0.59679261, 0.98000756]])

In [25]:
# array (3x3) with values<2 
np.random.randint(2,size=(3,3))

array([[0, 1, 0],
       [0, 1, 1],
       [0, 1, 0]])

In [26]:
# array (3x3) with -4<values<0 
np.random.randint(-4,0,size=(3,3))

array([[-1, -3, -2],
       [-1, -1, -1],
       [-4, -3, -4]])

# Numpy Min, ArgMin, Max, ArgMax

In [2]:
import numpy as np

In [3]:
x= np.array([50,600,10,14,10])

In [4]:
print(np.min(x))

10


In [5]:
print(np.argmin(x))

2


In [6]:
print(np.max(x))

600


In [7]:
print(np.argmax(x))

1


# Accessing/Changing specific elements, row, columns, etc

In [8]:
import numpy as np

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element [r,c]
a[1,2]

10

In [11]:
a[0,6]

7

In [12]:
# index is higher than the array size = error!
a[0,11]

IndexError: index 11 is out of bounds for axis 1 with size 7

In [13]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[:,3]

array([ 4, 11])

In [15]:
# [  ,start_index:end_index : stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [16]:
#change an element from the array
a[0,0]=1000
print(a)

[[1000    2    3    4    5    6    7]
 [   8    9   10   11   12   13   14]]
